// src/components/templates/Portal/Portal.component.tsx
import React, { useState, useMemo, MouseEvent } from 'react';
import { Drawer, IconButton, Menu, MenuItem, Avatar } from '@mui/material';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import PersonIcon from '@mui/icons-material/Person';
interface PortalTab  {
  label: string;
  route: {
    path: string;
  };
  icon: string;
};

interface PortalProps {
  tabs?: PortalTab[];
  user?: {
    first_name: string,
    email: string,
    last_name: string,
  },
  logout?: () => void;
};

const Portal: React.FC<PortalProps> = (props) => {
    const {tabs = [], logout, user = {
        first_name: "Unknown",
        last_name: "Name",
        email: "",
    }} = props;
const {first_name, last_name, email} = user;
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [menuAnchorEl, setMenuAnchorEl] = useState<null | HTMLElement>(null);
  const pathname = usePathname();
  const activeChildRoute = pathname.split('/').pop();

  const toggleDrawer = () => setDrawerOpen(!drawerOpen);
  
  const openMenu = (event: MouseEvent<HTMLDivElement>) => {
    setMenuAnchorEl(event.currentTarget);
  };
  
  const closeMenu = () => setMenuAnchorEl(null);

  const memoizedTabs = useMemo(() => (
    tabs.map((tab, index) => (
      <Link
        key={index}
        href={`/portal/${tab.route.path}`}
        passHref
        className={`group w-full p-4 flex items-center justify-start gap-2 rounded-lg cursor-pointer hover:bg-gray-200 ${activeChildRoute === tab.route.path ? 'bg-gray-200' : ''}`}
      >
        <div className={`w-6 h-6 flex items-center justify-center p-1 ${activeChildRoute === tab.route.path ? 'text-bridge-black' : 'text-gray-400'}`}>
          <svg width="100%" height="100%">
            <use href={`/assets/icons/${tab.icon}.svg#${tab.icon}`} />
          </svg>
        </div>
        <p className={`text-[16px] ${activeChildRoute === tab.route.path ? 'font-bold text-bridge-black' : 'font-semibold text-gray-400'}`}>
          {tab.label}
        </p>
      </Link>
    ))
  ), [tabs, activeChildRoute]);

  return (
    <div className="flex flex-col md:flex-row items-start relative h-screen w-screen">
      <Drawer open={drawerOpen} onClose={toggleDrawer}>
        <div className="box-border flex flex-col gap-24 py-5 px-6">
          <div className="flex flex-col items-start gap-8">
            <div className="flex items-center justify-between w-full min-w-[300px]">
              <img className="max-w-[100px]" alt="Bridge Financial logo" src="/assets/images/Bridge-logo.png" />
              <IconButton onClick={toggleDrawer}>
                <span className="material-icons">close</span>
              </IconButton>
            </div>
            <div className="flex flex-col gap-4">
              <div className="flex flex-row items-center justify-start gap-5">
              <Avatar
      sx={{ width: 64, height: 64, bgcolor: 'gray.50' }} // 64px is equivalent to 16 in tailwind (w-16, h-16)
    >
      <PersonIcon />
    </Avatar>                <div className="space-y-1">
                  <p>
                    <strong>
                      {first_name} {last_name}
                    </strong>
                  </p>
                  <p>{email}</p>
                </div>
              </div>
              <div className="flex items-center gap-2 cursor-pointer" onClick={logout}>
                <span className="material-icons" color="secondary">logout</span>
                <p className="no-underline text-bridge-black">Log out</p>
              </div>
            </div>
          </div>
          <div className="flex flex-col w-full items-stretch justify-start gap-1">
            {memoizedTabs}
          </div>
        </div>
      </Drawer>
      <div className="h-screen w-screen flex flex-col md:flex-row items-stretch justify-stretch">
        <div className="sticky w-screen top-0 md:hidden bg-white">
          <div className="w-full grid grid-cols-3 p-4">
            <div>
              <IconButton onClick={toggleDrawer}>
                <span className="material-icons">menu</span>
              </IconButton>
            </div>
            <div className="flex items-center justify-center">
              <Link href="/" passHref>
                <img className="max-w-[100px]" alt="Bridge Financial logo" src="/assets/images/Bridge-logo.png" />
              </Link>
            </div>
            <div></div>
          </div>
          <div className="w-full h-[3px] linear-gradient-orange-purple-blue"></div>
        </div>
        <div className="h-full grow-0 hidden md:flex flex-col basis-[250px] box-border py-7 px-5 bg-white border-0 border-r border-solid border-gray-300">
          <Link href="/" passHref className="mx-auto mb-16">
            <img className="max-w-[120px]" alt="Bridge logo" src="/assets/images/Bridge-logo.png" />
          </Link>
          <div className="flex flex-col w-full items-stretch justify-start gap-1">
            {memoizedTabs}
          </div>
        </div>
        <div className="grow bg-gray-50 w-full overflow-auto">
          <div className="w-full max-w-[1200px] px-4 py-8 md:px-10 md:py-6 box-border">
            <div className="flex items-center justify-between w-full text-bridge-black py-2">
              <h1>{activeChildRoute ? activeChildRoute[0].toUpperCase() + activeChildRoute.slice(1) : ''}</h1>
              <div className="hidden md:flex items-center gap-2 p-2 cursor-pointer hover:bg-gray-200" onClick={openMenu}>
                <div className="w-16 h-16 rounded-lg bg-white flex items-center justify-center">
                  <Avatar>
                    {first_name? first_name[0]: null}
                  </Avatar>
                </div>
                <span className="material-icons" color="secondary">keyboard_arrow_down</span>
              </div>
              <Menu anchorEl={menuAnchorEl} open={Boolean(menuAnchorEl)} onClose={closeMenu}>
                <MenuItem onClick={logout}>Log out</MenuItem>
              </Menu>
            </div>
            <div>
              {/* Next.js Page Content Goes Here */}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Portal;

// oldcode/portal.component.ts
import { FormSubmission } from '@/app/types';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, NavigationEnd, Router, RouterModule } from '@angular/router';
import { OnboardingFormSuccessComponent } from '@/app/routes/onboarding-form-success/onboarding-form-success.component';
import { environment } from '@/environments/environment';
import { CheckListItemComponent } from '@/app/components/check-list-item/check-list-item.component';
import { PORTAL_TABS, PortalTab } from '@/app/app.routes';
import { Subscription, filter } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatSidenavModule } from '@angular/material/sidenav';
import { AuthService } from '@/app/auth';
import { MatMenuModule } from '@angular/material/menu';
import { AvatarComponent } from '@/app/components/avatar/avatar.component';

export type CheckListItem = {
  title: string;
  content: string;
  completed: boolean;
  routerLink: string;
  formId?: number;
};

@Component({
  selector: 'app-portal',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    OnboardingFormSuccessComponent,
    CheckListItemComponent,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatMenuModule,
    AvatarComponent,
  ],
  templateUrl: './portal.component.html',
  styleUrl: './portal.component.scss',
})
export class PortalComponent implements OnInit {
  public forms: any[] = [];
  public formSubmissions: Record<number, FormSubmission> = {};
  public checkListItems: CheckListItem[] = [];
  public tabs: PortalTab[] = PORTAL_TABS;
  activeChildRoute: string = '';
  private routerSubscription: Subscription | undefined;

  constructor(
    private http: HttpClient,
    private router: Router,
    private route: ActivatedRoute,
    public auth: AuthService,
  ) {}

  public ngOnInit() {
    this.http
      .get(`${environment['DJANGO_API_BASE_URL'] ?? 'http://localhost:8000'}/api/forms/`)
      .subscribe((forms: any) => {
        this.forms = forms.results;
        this.checkListItems.push(
          ...this.forms.map((form) => {
            return {
              title: form.name,
              content: `Complete the <strong>${form.name}</strong> Form`,
              completed: false,
              routerLink: `/forms/${form.id}`,
              formId: form.id,
            };
          }),
        );
        this.forms.forEach((form) => {
          this.http
            .get<FormSubmission>(
              `${environment['DJANGO_API_BASE_URL'] ?? 'http://localhost:8000'}/api/form-submission/${form.id}`,
            )
            .subscribe(
              (value) => {
                this.formSubmissions[form.id] = value;
              },
              (err) => {},
            );
        });
      });

    // Subcribe to the router changes
    this.routerSubscription = this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe(() => {
        this.setActiveChildRoute();
      });

    // Set the active route on initial load
    this.setActiveChildRoute();
  }

  ngOnDestroy(): void {
    if (this.routerSubscription) {
      this.routerSubscription.unsubscribe();
    }
  }

  public logout() {
    this.auth.logout().subscribe(() => {
      this.router.navigate(['/login']);
    });
  }

  private setActiveChildRoute(): void {
    let child = this.route.firstChild;
    while (child) {
      if (child.snapshot.url.length) {
        this.activeChildRoute = child.snapshot.url[0].path;
        break;
      }
      child = child.firstChild;
    }
  }
}

<mat-drawer-container autosize hasBackdrop="true" class="flex flex-col md:flex-row items-start relative">
  <mat-drawer #drawer mode="over">
    <div class="box-border flex flex-col gap-24 py-5 px-6">
      <div class="flex flex-col items-start gap-8">
        <div class="flex items-center justify-between w-full min-w-[300px]">
          <img class="max-w-[100px]" alt="Bridge Financial logo" src="/assets/images/Bridge-logo.png" />
          <button mat-icon-button class="text-left" (click)="drawer.toggle()">
            <mat-icon>close</mat-icon>
          </button>
        </div>
        <div class="flex flex-col gap-4">
          <div class="flex flex-row items-center justify-start gap-5">
            <app-avatar />
            <div class="space-y-1">
              <p>
                <strong
                  >{{ this.auth.getUser()?.first_name || 'Unknown' }}
                  {{ this.auth.getUser()?.last_name || 'Name' }}</strong
                >
              </p>
              <p>{{ this.auth.getUser()?.email }}</p>
            </div>
          </div>
          <a class="flex items-center justify-start gap-2 cursor-pointer" (click)="logout()">
            <mat-icon color="accent">logout</mat-icon>
            <p class="no-underline text-bridge-black">Log out</p>
          </a>
        </div>
      </div>
      <div class="flex flex-col w-full items-stretch justify-start gap-1">
        @for (tab of tabs; track $index) {
          <a
            [ngClass]="{ 'bg-gray-200': activeChildRoute === tab.route.path }"
            class="group w-full p-4 flex items-center justify-start gap-2 rounded-lg cursor-pointer hover:bg-gray-200"
            [routerLink]="['/portal/' + tab.route.path]"
            (click)="drawer.toggle()"
          >
            <div
              class="w-6 h-6 flex items-center justify-center p-1 group-hover:text-bridge-black"
              [ngClass]="{
                'text-gray-400': activeChildRoute !== tab.route.path,
                'text-bridge-black': activeChildRoute === tab.route.path
              }"
            >
              <svg width="100%" height="100%">
                <use
                  [attr.xlink.href]="'/assets/icons/' + tab.icon + '.svg#' + tab.icon"
                  [attr.href]="'/assets/icons/' + tab.icon + '.svg#' + tab.icon"
                ></use>
              </svg>
              <!-- <img class="w-full" src="{{ '/assets/icons/' + tab.icon + '.svg' }}" /> -->
            </div>
            <p
              [ngClass]="{
                'font-semibold text-gray-400': activeChildRoute !== tab.route.path,
                'font-bold text-bridge-black': activeChildRoute === tab.route.path
              }"
              class="text-[16px] group-hover:text-bridge-black group-hover:font-bold"
            >
              {{ tab.label }}
            </p>
          </a>
        }
      </div>
    </div>
  </mat-drawer>
  <mat-drawer-content>
    <div class="h-screen w-screen flex flex-col md:flex-row items-stretch justify-stretch">
      <!-- MOBILE HEADER -->
      <div class="sticky w-screen top-0 md:hidden bg-white">
        <div class="w-full grid grid-cols-3 p-4">
          <!-- LEFT MOBILE HEADER -->
          <div>
            <button mat-icon-button class="text-left" (click)="drawer.toggle()">
              <mat-icon>menu</mat-icon>
            </button>
          </div>
          <!-- CENTER MOBILE HEADER -->
          <div class="flex items-center justify-center">
            <a [routerLink]="['/']">
              <img class="max-w-[100px]" alt="Bridge Financial logo" src="/assets/images/Bridge-logo.png" />
            </a>
          </div>
          <!-- RIGHT MOBILE HEADER -->
          <div></div>
        </div>
        <div class="w-full h-[3px] linear-gradient-orange-purple-blue"></div>
      </div>
      <!-- DESKTOP NAV -->
      <div
        class="h-full grow-0 hidden md:flex flex-col basis-[250px] box-border py-7 px-5 bg-white border-0 border-r border-solid border-gray-300"
      >
        <a class="mx-auto mb-16" [routerLink]="['/']">
          <img class="max-w-[120px]" alt="Bridge logo" src="/assets/images/Bridge-logo.png" />
        </a>
        <div class="flex flex-col w-full items-stretch justify-start gap-1">
          @for (tab of tabs; track $index) {
            <a
              [ngClass]="{ 'bg-gray-200': activeChildRoute === tab.route.path }"
              class="group w-full p-4 flex items-center justify-start gap-2 rounded-lg cursor-pointer hover:bg-gray-200"
              [routerLink]="['/portal/' + tab.route.path]"
            >
              <div
                class="w-6 h-6 flex items-center justify-center p-1 group-hover:text-bridge-black"
                [ngClass]="{
                  'text-gray-400': activeChildRoute !== tab.route.path,
                  'text-bridge-black': activeChildRoute === tab.route.path
                }"
              >
                <svg width="100%" height="100%">
                  <use
                    [attr.xlink.href]="'/assets/icons/' + tab.icon + '.svg#' + tab.icon"
                    [attr.href]="'/assets/icons/' + tab.icon + '.svg#' + tab.icon"
                  ></use>
                </svg>
                <!-- <img class="w-full" src="{{ '/assets/icons/' + tab.icon + '.svg' }}" /> -->
              </div>
              <p
                [ngClass]="{
                  'font-semibold text-gray-400': activeChildRoute !== tab.route.path,
                  'font-bold text-bridge-black': activeChildRoute === tab.route.path
                }"
                class="text-[16px] group-hover:text-bridge-black group-hover:font-bold"
              >
                {{ tab.label }}
              </p>
            </a>
          }
        </div>
      </div>
      <!-- BODY -->
      <div class="grow bg-gray-50 w-full overflow-auto">
        <div class="w-full max-w-[1200px] px-4 py-8 md:px-10 md:py-6 box-border">
          <!-- Body Header and Profile Dropdown -->
          <div class="flex items-center justify-between w-full text-bridge-black py-2">
            <h1>{{ activeChildRoute[0].toLocaleUpperCase() + activeChildRoute.slice(1) }}</h1>
            <a
              class="hidden md:flex items-center gap-2 p-2 cursor-pointer hover:bg-gray-200"
              [matMenuTriggerFor]="menu"
            >
              <div class="w-16 h-16 rounded-lg bg-white flex items-center justify-center">
                <mat-icon color="accent">person</mat-icon>
              </div>
              <mat-icon color="accent">keyboard_arrow_down</mat-icon>
            </a>
            <mat-menu #menu="matMenu" class="p-4">
              <div class="space-y-4">
                <div class="space-y-1">
                  <p>
                    <strong
                      >{{ this.auth.getUser()?.first_name || 'Unknown' }}
                      {{ this.auth.getUser()?.last_name || 'Name' }}</strong
                    >
                  </p>
                  <p>{{ this.auth.getUser()?.email }}</p>
                </div>
                <a class="flex items-center justify-start gap-2 cursor-pointer" (click)="logout()">
                  <mat-icon color="accent">logout</mat-icon>
                  <p class="no-underline text-bridge-black">Log out</p>
                </a>
              </div>
            </mat-menu>
          </div>
          <!-- Outlet -->
          <router-outlet />
        </div>
      </div>
    </div>
  </mat-drawer-content>
</mat-drawer-container>
